services:
  db:
    image: postgres:latest
    container_name: desafio-primeira-api-com-nodejs-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_test:
    image: postgres:latest
    container_name: desafio-primeira-api-com-nodejs-db-test
    ports:
      - "5433:5432"
    env_file:
      - .env.test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_test_data:
